apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: 54.242.130.89:8081/repository/docker-hosted/backend-app:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
  namespace: default
spec:
  selector:
    app: backend-app
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
